apiVersion: apps/v1
kind: Deployment
metadata:
  name: taska2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: taska2
          image: nuszengyuting/node-server
          ports:
            - containerPort: 3000
